### ISSUE TITLE
API not working!

### ISSUE THREAD

**Issue by blackprince001** [king-phyte/english-dictionary#5]
Very bad code written. You should be ashamed of yourself for the atrocious blasphemy you have caused.

**Comment by king-phyte** [comment]
You can rant, or you can give me steps to reproduce the said problem. You choose

**Comment by blackprince001** [comment]
don't cry master

**Comment by king-phyte** [comment]
False alarm? Cos if there is a bug, I wanna fix it ASAP

**Comment by blackprince001** [comment]
oh don't worry, there isn't any. you really need to quit coding you know, this shit ain't for everyone you see

**Comment by king-phyte** [comment]
XD Maybe we should continue this convo on Telegram. I am closing the issue.
